module.exports = {
  docs: {
    Overview: [
      "gettingStarted",
      "registeringState",
      "usingState",
      "composingState",
      "examples/index",
      "optionalSelectors",
      "modernImmutability",
      "actionsAreFunctions",
      "stateDrivenFunctions",
      "coreConcepts"
    ],
    API: [
      {
        type: "category",
        label: "carry-on-store",
        items: [
          {
            type: "autogenerated",
            dirName: "api/carry-on-store"
          }
        ]
      },
      {
        type: "category",
        label: "carry-on-react",
        items: [
          {
            type: "autogenerated",
            dirName: "api/carry-on-react"
          }
        ]
      },
      {
        type: "category",
        label: "carry-on-react-forms",
        items: [
          {
            type: "autogenerated",
            dirName: "api/carry-on-react-forms"
          }
        ]
      },
      {
        type: "category",
        label: "carry-on-react-router",
        items: [
          {
            type: "autogenerated",
            dirName: "api/carry-on-react-router"
          }
        ]
      }
    ]
  }
};
